services:
  - type: web
    name: lumi-bot
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: YANDEX_API_KEY
        sync: true
      - key: CATALOG_ID
        sync: true
      - key: TELEGRAM_TOKEN
        sync: true
